# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
    session: true

    router:
        utf8: true
        strict_requirements: ~
        # On utilise LA SEULE source de vérité pour les liens absolus (CLI & Web)
        default_uri: 'https://localhost'
        http_port: 80
        # Correction de la coquille : 443 est le port HTTPS standard
        https_port: 443
