# 1. LA DÉCLARATION GLOBALE (C'est ce qu'il te manquait !)
monolog:
    channels:
        - deprecation

# 2. TON ENVIRONNEMENT DE DEV (Inchangé)
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

# 3. TON ENVIRONNEMENT DE TEST (Inchangé)
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

# 4. TON ENVIRONNEMENT DE PROD (Avec Sentry/GlitchTip)
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [404, 405]
                channels: ["!deprecation"]
                buffer_size: 50

            grouped:
                type: group
                members: [nested, sentry]

            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json

            sentry:
                type: service
                id: Sentry\Monolog\Handler

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
