framework:
    notifier:
        chatter_transports:
            workspace_failed_verify: '%env(WORKSPACE_FAILED_SLACK_DSN)%'
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
