security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Domain\User\Entity\User
                property: email

    # 1. LA PYRAMIDE PARFAITE (Chaque rôle hérite du précédent)
    role_hierarchy:
        ROLE_CLIENT:           [ ROLE_USER ]
        ROLE_WORKSPACE_COLLAB: [ ROLE_USER ]
        ROLE_WORKSPACE_ADMIN:  [ ROLE_WORKSPACE_COLLAB ]
        # L'admin a les droits du Workspace Admin + le droit d'usurper une identité pour le support
        ROLE_ADMIN:            [ ROLE_WORKSPACE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_SUPER_ADMIN:      [ ROLE_ADMIN ]

    firewalls:
        image_resolver:
            pattern: ^/media/cache/resolve
            security: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            custom_authenticator:
                - App\Infrastructure\Security\MagicLinkAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_dashboard

            logout:
                path: app_logout
                target: app_login

            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

            # 2. ACTIVATION DU SWITCH USER (Pour le support technique Kysure)
            switch_user: true

            # NOTE POUR PLUS TARD : Activer la 2FA ici (Vital pour une RegTech)

    access_control:
        # Les routes publiques (Accessibles sans être connecté)
        - { path: ^/portal/, roles: PUBLIC_ACCESS }
        - { path: ^/api/stripe/webhook, roles: PUBLIC_ACCESS }
        - { path: ^/api/track, roles: PUBLIC_ACCESS } # 3. La route de tracking Stimulus !
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # Les routes protégées (Grâce à la hiérarchie propre, ROLE_USER suffit)
        - { path: ^/2fa/, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/mon-compte/, roles: ROLE_CLIENT } # L'admin y aura accès grâce à la hiérarchie !
        - { path: ^/app/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
