<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260318172747 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan VARCHAR(50) NOT NULL, extra_seats INT DEFAULT 0 NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, stripe_subscription_id VARCHAR(255) DEFAULT NULL, workspace_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4778A0182D40A1F ON subscriptions (workspace_id)');
        $this->addSql('CREATE TABLE workspace_members (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(50) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, workspace_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9D9D39F4A76ED395 ON workspace_members (user_id)');
        $this->addSql('CREATE INDEX IDX_9D9D39F482D40A1F ON workspace_members (workspace_id)');
        $this->addSql('CREATE UNIQUE INDEX idx_unique_user_workspace ON workspace_members (user_id, workspace_id)');
        $this->addSql('ALTER TABLE subscriptions ADD CONSTRAINT FK_4778A0182D40A1F FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workspace_members ADD CONSTRAINT FK_9D9D39F4A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workspace_members ADD CONSTRAINT FK_9D9D39F482D40A1F FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workspaces ADD siret VARCHAR(14) DEFAULT NULL');
        $this->addSql('ALTER TABLE workspaces ADD legal_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE workspaces ADD address TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE workspaces ADD logo_filename VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE workspaces ADD industry VARCHAR(50) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FE8F3CB5E237E06 ON workspaces (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FE8F3CB26E94372 ON workspaces (siret)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE subscriptions DROP CONSTRAINT FK_4778A0182D40A1F');
        $this->addSql('ALTER TABLE workspace_members DROP CONSTRAINT FK_9D9D39F4A76ED395');
        $this->addSql('ALTER TABLE workspace_members DROP CONSTRAINT FK_9D9D39F482D40A1F');
        $this->addSql('DROP TABLE subscriptions');
        $this->addSql('DROP TABLE workspace_members');
        $this->addSql('DROP INDEX UNIQ_7FE8F3CB5E237E06');
        $this->addSql('DROP INDEX UNIQ_7FE8F3CB26E94372');
        $this->addSql('ALTER TABLE workspaces DROP siret');
        $this->addSql('ALTER TABLE workspaces DROP legal_name');
        $this->addSql('ALTER TABLE workspaces DROP address');
        $this->addSql('ALTER TABLE workspaces DROP logo_filename');
        $this->addSql('ALTER TABLE workspaces DROP industry');
    }
}
