# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    geoip_db_path: '%env(resolve:GEOIP_DB_PATH)%'
    app.kyc_upload_directory: '%kernel.project_dir%/public/uploads/kyc'
    router.request_context.host: 'kysure.fr'
    router.request_context.scheme: 'https'
    router.request_context.base_url: ''
    tempStorageDir: '%kernel.project_dir%/var/uploads/kyc_temp'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $mindeeApiKey: '%env(MINDEE_API_KEY)%'
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            # 👇 AJOUTE CES LIGNES POUR TON ARCHITECTURE DDD 👇
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/Event/'
            - '../src/Application/DTO/'
            - '../src/Application/Request/'
    Mindee\ClientV2:
        arguments:
            $apiKey: '%env(MINDEE_API_KEY)%'
    App\Infrastructure\Ocr\MindeeProvider: ~
    App\Infrastructure\Ocr\FakeOcrProvider: ~

    App\Infrastructure\Ocr\OcrFactory: ~

        # 🚀 ON DÉFINIT L'INTERFACE VIA LE FACTORY
    App\Domain\Port\OcrProviderInterface:
        factory: [ '@App\Infrastructure\Ocr\OcrFactory', 'create' ]
        arguments:
            $mode: '%env(OCR_MODE)%'

    App\Application\Kyc\UseCase\UploadKycDocumentUseCase:
        arguments:
            $tempStorageDir: '%tempStorageDir%'

    # Définition des alias nommés pour matcher la variable d'env
    real_ocr_provider:
        alias: App\Infrastructure\Ocr\MindeeProvider

    mock_ocr_provider:
        alias: App\Infrastructure\Ocr\FakeOcrProvider
    Aws\S3\S3Client:
        arguments:
            -   version: 'latest'
                region: '%env(S3_REGION)%'
                endpoint: '%env(S3_ENDPOINT)%'
                credentials:
                    key: '%env(S3_ACCESS_KEY)%'
                    secret: '%env(S3_SECRET_KEY)%'
                    # Use_path_style_endpoint est souvent nécessaire pour les S3 alternatifs à AWS
                use_path_style_endpoint: true
    App\Infrastructure\Storage\LocalDocumentStorage:
        arguments:
            $baseUploadDirectory: '%app.kyc_upload_directory%'
    App\Domain\Port\DocumentStorageInterface: '@App\Infrastructure\Storage\ScalewayS3DocumentStorage'
    App\Infrastructure\Billing\Controller\StripeWebhookController:
        arguments:
            $stripeWebhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
