<?php

namespace App\Domain\Shared\Enum;

enum ErrorCode: string
{
    case WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND';
    case KYC_ALREADY_VALIDATED = 'KYC_ALREADY_VALIDATED';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND';
    case PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
}
