; https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading
opcache.preload_user = root
opcache.preload = /app/config/preload.php
; https://symfony.com/doc/current/performance.html#don-t-check-php-files-timestamps
opcache.validate_timestamps = 0

; 🛡️ KYSURE OPS : Alignement des timeouts et mémoire PHP 8.4
max_execution_time = 60
max_input_time = 60
memory_limit = 512M

; Optimisation FrankenPHP Worker Thread Pool pour 4 Go RAM
opcache.enable_cli = 1
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 128
